# Playbook to provision Vagrant VM for e-commerce application
- name: Provision e-commerce application
  hosts: all
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    # Create project directory
    - name: Create project directory
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: terraform
        group: terraform
        mode: '0755'

  roles:
    # Configure system and install base dependencies
    - common_config
    # Install Docker and Docker Compose
    - docker_setup
    # Install and configure MongoDB
    # - mongodb_setup
    # Deploy the application
    - app_deployment