apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
  namespace: yolo-app
spec:
  selector:
    app: yolo-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer