apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-client
  namespace: yolo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
      - name: yolo-client
        image: mulikevs/mulikevs-yolo-client:v1.0.1
        ports:
        - containerPort: 3000
